[project]
name = "ttsnewscast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "TTS>=0.22.0",
    "pip>=25.0.1",
    "newspaper4k>=0.9.5",
    "piper-tts>=1.4.2",
    "uvicorn>=0.46.0",
    "lingua-language-detector>=2.1.1",
]
